name: Build
on:
  push:
    branches:
      - main
  pull_request:
     branches:
      - main
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.organization=sakship3103
            -Dsonar.projectKey=SakshiP3103_Sonarqube-poc

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}